### ISSUE TITLE
Oneplus 7 pro GM1917;  Error 182.5

### ISSUE THREAD

**Issue by MitchRapp01** [leegarchat/dfe-neo-v2#8]
On OOS 11.  Tried flashing dfe-neo v2.5.1.  It began installing but then suddenly stopped and gave me the following message:

Failed to find in ramdisk boot/vendor_boot: fstab.qcom
!!!Exiting with error:  182.5!!!

Tried googling this, asked gpt, but I can't find much information that would give me a hint as to why it's not working.

Here is the log.

[neo_file_28_10_24-21-09-43.log](https://github.com/user-attachments/files/17550829/neo_file_28_10_24-21-09-43.log)

Edit. I think I mightve used the wrong file.

**Comment by marcocancarini** [comment]
Sorry to reopen this issue.
I have the same device, may I ask you how did you manage to fix it?
Which file did you flash? I tried flashing the arm64 and the universal file both in twrp and magisk, but I have the 182.5 error

**Comment by SudoZeus-Code** [comment]
i am having the same issue as above. using both arm64 and Universal version 2.5.1.

**Comment by marcocancarini** [comment]
@SudoZeus-Code may I ask you which device do you have?
